### ISSUE TITLE
Unable to deploy stack

### ISSUE THREAD

**Issue by FooBarRaz** [fernando-mc/aws-http-api-node-cognito#1] opened 2020-03-21 22:57 UTC
I'm unable to deploy this stack. I get an error saying 
```

  Error --------------------------------------------------

  Error: The CloudFormation template is invalid: Template format error: Every Resources object must contain a Type member.
      at provider.request.catch.error (/home/raz/.config/yarn/global/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:19:13)
      at tryCatcher (/home/raz/.config/yarn/global/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/raz/.config/yarn/global/node_modules/bluebird/js/release/promise.js:517:31)
      at Promise._settlePromise (/home/raz/.config/yarn/global/node_modules/bluebird/js/release/promise.js:574:18)
      at Promise._settlePromise0 (/home/raz/.config/yarn/global/node_modules/bluebird/js/release/promise.js:619:10)
      at Promise._settlePromises (/home/raz/.config/yarn/global/node_modules/bluebird/js/release/promise.js:695:18)
      at _drainQueueStep (/home/raz/.config/yarn/global/node_modules/bluebird/js/release/async.js:138:12)
      at _drainQueue (/home/raz/.config/yarn/global/node_modules/bluebird/js/release/async.js:131:9)
      at Async._drainQueues (/home/raz/.config/yarn/global/node_modules/bluebird/js/release/async.js:147:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/raz/.config/yarn/global/node_modules/bluebird/js/release/async.js:17:14)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:120:23)
```

I assume this is happening because the `HttpApiResource` but I don't know enough about the Serverless framework to be able to fix it.

**Comment by fernando-mc** [comment] 2020-03-23 03:06
@FooBarRaz Can you share the serverless.yml file you are using? I'm not able to reproduce this myself.

It might also be helpful if you have the version info for the framework version you're using?

**Comment by FooBarRaz** [comment] 2020-03-24 15:01
@fernando-mc  I'm running the `serverless.yml` file in the `master` branch of you repo, just with the org name changed to my own (and I've created an app on the Serverless dashboard). 

I'm using the latest version of the servereless framework (core: `1.67.0` and SDK: `2.3.0`)

**Comment by fernando-mc** [comment] 2020-03-24 21:58
That's super strange! I just tested this and it seems to be working okay? Can you DM me in the serverless community slack so we can set a time to debug it? 

serverless.com/slack
My member id is - UMZ8N7ZRQ

**Comment by sprour** [comment] 2020-04-06 22:19
I have the same issue. I also commented authorizer and deployed it, but it didn't show me any endpoint. I checked it in aws console and there's no any api service deployed. When I changed httpApi to http then it deployed successfully. My sls version is 
`Framework Core: 1.62.0 (standalone)
Plugin: 3.3.0
SDK: 2.3.0
Components Core: 1.1.2
Components CLI: 1.4.0
`

**Comment by fernando-mc** [comment] 2020-04-06 22:27
@sprour I think you may need to upgrade your framework version. I don't think v1.62.0 has the functionality that this uses. I wasn't able to reproduce the issue when running 1.67 or above.

**Comment by sprour** [comment] 2020-04-06 22:36
@fernando-mc sorry, my fault. yes it works! thank you! :)

**Comment by fernando-mc** [comment] 2020-04-07 00:09
No worries! @FooBarRaz I'm going to close this for now. Feel free to reach out again and we can troubleshoot in the Slack.

**Closed as completed by fernando-mc** 2020-04-07 00:09 UTC
